import Head from 'next/head'

import { useEffect, useState } from "react"
import Background from "../components/Background"
import LoaderPage from "../components/LoaderPage"

import { useReactiveVar } from "@apollo/client"

import client, { currentMenu, currentWork, showMenu } from "../../apollo-client"
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({profileData}) {
  const menuId = useReactiveVar(currentMenu)
  const workId = useReactiveVar(currentWork)
  const sideMenu = useReactiveVar(showMenu)
  const [loaderPage, setLoaderPage] = useState(true)

  useEffect(() => {
    const timeoutId = setTimeout(() => setLoaderPage(false), 3500)
    return () => {
      clearTimeout(timeoutId)
    }
  }, [setLoaderPage])

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
      {loaderPage && <LoaderPage />}

<Background />
        <div className={styles.description}>
         
        </div>

        <div className={styles.center}>
         
        </div>

        <div className={styles.grid}>
          
        </div>
      </main>
    </>
  )
}
